function out=subbackground_BGplusScat(strucin,t,l)

strucout = strucin;
back=mean(strucin.smootheddata(:,strucin.time>t(1)&strucin.time<t(2)),2);
figure
plot(back)
title('Background')
%%no scatter part, before t0
strucout.smootheddata(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6)...
    =strucout.smootheddata(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6)...
    -repmat(back(or(strucin.lam<l(1), strucin.lam>l(2))),1,size(strucin.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6),2));
%%no scatter part after t0
strucout.smootheddata(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6)...
    =strucout.smootheddata(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6)...
    +repmat(back(or(strucin.lam<l(1), strucin.lam>l(2))),1,size(strucin.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6),2));
%%scattering (only until 20 us)
strucout.smootheddata(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5)...
    =strucout.smootheddata(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5)...
    -repmat(back(and(strucin.lam>=l(1), strucin.lam <= l(2))),1,size(strucin.data(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5),2));
%% Same for the not smoothed data
strucout.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6)...
    =strucout.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6)...
    -repmat(back(or(strucin.lam<l(1), strucin.lam>l(2))),1,size(strucin.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time<1.7e-6),2));
%%no scatter part after t0
strucout.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6)...
    =strucout.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6)...
    +repmat(back(or(strucin.lam<l(1), strucin.lam>l(2))),1,size(strucin.data(or(strucin.lam<l(1), strucin.lam>l(2)),strucin.time>=1.7e-6),2));
%%scattering (only until 20 us)
strucout.data(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5)...
    =strucout.data(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5)...
    -repmat(back(and(strucin.lam>=l(1), strucin.lam <= l(2))),1,size(strucin.data(and(strucin.lam>=l(1), strucin.lam <= l(2)),strucin.time<2e-5),2));

out=strucout;
